name: "paperless-app"
version: '3.8'

services:
  server:
    build: PaperlessRestServer/
    container_name: my-server
    volumes:
      - server-data:/var/myapp
    ports:
      - "8080:8080" # Expose the server on port 8000
    networks: 
      - app-network

  ui:
    build: PaperlessUI/
    container_name: my-ui
    volumes:
      - ui-data:/var/www
    ports:
      - "4200:4200" # Expose the UI on port 80
    depends_on:
      - server
    networks: 
      - app-network

volumes:
  server-data:
  ui-data:

networks:
  app-network:
