name: "paperless-app"
version: '3.8'

services:
  server:
    build: PaperlessRestServer/
    container_name: my-server
    volumes:
      - server-data:/var/myapp
    ports:
      - "8080:8080" # Expose the server on port 8000
    networks: 
      - app-network
    depends_on:
      - postgres

  #ui:
    #build: PaperlessUI/
    #container_name: my-ui
    #volumes:
     # - ui-data:/var/www
    #ports:
     # - "4200:4200" # Expose the UI on port 80
    #depends_on:
     # - server
    #networks: 
     # - app-network


  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: adminpassword
    command: server --console-address ":9001" /data




  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: newpassword
      POSTGRES_USER: myuser
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - my_dbdata:/var/lib/postgresql/data

  rabbitmq:
    container_name: "rabbitmq"
    image: rabbitmq:3.8-management-alpine
    ports:
        #RabbitMQ instance
      - '5672:5672'
        #Web Interface
      - '15672:15672' 

volumes:
  server-data:
  ui-data:
  my_dbdata:
  minio_storage:

networks:
  app-network:
